#!/bin/bash


#Take the fasta files generated by profileHMMbuild.py and build them into models (as the
#original script is struggling with some of the steps due to dependancies not being 
#installed).

#This will run muscle across all of the files and then run hmmbuild across the muscle 
#files finally followed by building a single hmm profile set. 


let "fileNum = 0"
for file in *.faa

do

filename=`basename $file .faa`
echo $filename

echo "Running muscle on $filename"
muscle -in $filename.faa -out $filename.mcl

echo "Running hmmbuild on $filename"
hmmbuild --informat afa -n $filename -o $filename.log --cpu 2 $filename.hmm $filename.mcl

done

mkdir logs 
mv *0.log ./logs
mv *1.log ./logs
mv *2.log ./logs
mv *3.log ./logs
mv *4.log ./logs
mv *5.log ./logs
mv *6.log ./logs
mv *7.log ./logs
mv *8.log ./logs
mv *9.log ./logs

mkdir fastaFiles 
mv *0.faa ./fastaFiles
mv *1.faa ./fastaFiles
mv *2.faa ./fastaFiles
mv *3.faa ./fastaFiles
mv *4.faa ./fastaFiles
mv *5.faa ./fastaFiles
mv *6.faa ./fastaFiles
mv *7.faa ./fastaFiles
mv *8.faa ./fastaFiles
mv *9.faa ./fastaFiles

mkdir mclFiles
mv *0.mcl ./mclFiles
mv *1.mcl ./mclFiles
mv *2.mcl ./mclFiles
mv *3.mcl ./mclFiles
mv *4.mcl ./mclFiles
mv *5.mcl ./mclFiles
mv *6.mcl ./mclFiles
mv *7.mcl ./mclFiles
mv *8.mcl ./mclFiles
mv *9.mcl ./mclFiles

mkdir HMMs
mv *0.hmm ./HMMs
mv *1.hmm ./HMMs
mv *2.hmm ./HMMs
mv *3.hmm ./HMMs
mv *4.hmm ./HMMs
mv *5.hmm ./HMMs
mv *6.hmm ./HMMs
mv *7.hmm ./HMMs
mv *8.hmm ./HMMs
mv *9.hmm ./HMMs

cd HMMs

let "fileNum = 0"
for file in *_1.hmm

do

filename=`basename $file _1.hmm`

cat *0.hmm >> ../$filename.hmm
cat *1.hmm >> ../$filename.hmm
cat *2.hmm >> ../$filename.hmm
cat *3.hmm >> ../$filename.hmm
cat *4.hmm >> ../$filename.hmm
cat *5.hmm >> ../$filename.hmm
cat *6.hmm >> ../$filename.hmm
cat *7.hmm >> ../$filename.hmm
cat *8.hmm >> ../$filename.hmm
cat *9.hmm >> ../$filename.hmm

done